-- Verify mi4cc:stage1 on snowflake

USE WAREHOUSE &warehouse;

SELECT * FROM MI4CC_DEV.TEST_SNOWFLAKE_DEPLOY_STG_ONE WHERE FALSE;
SELECT * FROM MI4CC_DEV.DEV_SNOWFLAKE_TEST_STG_ONE WHERE FALSE;

-- XXX Add verifications here.
